### ISSUE TITLE
Update to GluonFX plugins

### ISSUE THREAD

**Issue by jperedadnr** [FDelporte/ResistorCalculatorApp#10]
Use latest plugins 1.0.5 (for Maven and Gradle)

**Comment by FDelporte** [comment]
Managed to build https://github.com/FDelporte/JavaFXGameSnakeApp/ with latest versions, will update here the same way

**Comment by jperedadnr** [comment]
I have a PR almost ready

**Comment by jperedadnr** [comment]
Fixed with #11
