### ISSUE TITLE
MacOS App is blurry

### ISSUE THREAD

**Issue by ArloL** [FDelporte/ResistorCalculatorApp#12]
I am also trying some stuff with native JavaFX apps: https://github.com/ArloL/gitfx

And I was wondering if you ever noticed that the build result from GitHub Actions is blurry:

<img width="447" alt="Screenshot 2021-09-16 at 11 03 29" src="https://user-images.githubusercontent.com/195367/133583776-3cd549d2-0c4b-47ea-acc9-fd537149ee56.png">

Do you maybe have an idea what might be causing this? And maybe an idea on how to prevent this? Thanks :)

**Comment by FDelporte** [comment]
Did you try adding this already as your first call in the `start(Stage stage)`?

`System.setProperty("prism.lcdtext", "false");`

I started using this in all my JavaFX programs, but is not in this app (I notice now...)

**Comment by ArloL** [comment]
Thanks for answering so quickly :)

It did help with the text but sadly the buttons etc. still look like they are upscaled from non-retina resolution:

Before

<img width="752" alt="Screenshot 2021-09-16 at 16 19 24" src="https://user-images.githubusercontent.com/195367/133629048-614ff3e3-69f9-4e92-bff9-76ac9567fefa.png">

After

<img width="752" alt="Screenshot 2021-09-16 at 16 19 06" src="https://user-images.githubusercontent.com/195367/133629038-0528ade5-9c55-499a-a7dc-1ef458067e99.png">

**Comment by ArloL** [comment]
It has solved itself for my app. Thanks :)

**Comment by FDelporte** [comment]
@ArloL how was it fixed? with newer JavaFX version?

**Comment by ArloL** [comment]
Dont know. My guess is that something in the GitHub provided runner changed.
